services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: deel 
      POSTGRES_PASSWORD: deel 
      POSTGRES_DB: new_york_times
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - app_network

  ingestion:
    build: .
    image: ingestion-image
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres-db-volume:

networks:
  app_network:
    driver: bridge

